sudo: required
 
services:
  - docker

before_install:
  - docker build -t kiwisaffa/datacom client .
  - docker build -t kiwisaffa/datacom server .
 
 after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kiwisaffa/datacom:client
  - docker push kiwisaffa/datacom:server
  
  

