name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
language: node_js
node_js:
  - 14
  
  service:
    - docker

before_install:
  - docker build -t kiwisaffa/datacom client .
  - docker build -t kiwisaffa/datacom server .
 
 after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kiwisaffa/datacom:client
  - docker push kiwisaffa/datacom:server
  
  

