version: "2"
services:
    client:
        image: client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./datacom/app
            - /app/node_modules
        links:
            - server
    server:
        image: server
        restart: always
        ports:
            - "3002:3002"
        volumes:
            - ./datacom:/server
            - /app/node_modules
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
