name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t client . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build -t server . --file Dockerfile --tag my-image-name:$(date +%s)
