name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
        
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
